### ISSUE TITLE
注释不全

### ISSUE THREAD

**Issue by banfeng-git** [kuoihao/Serv00_Auto_Run#1]
你写的内容不全

**Comment by kuoihao** [comment]
谢谢，请问是哪里呢，我可以修正，这个其实就是ssh到主机上，启动run脚本。

**Comment by banfeng-git** [comment]
密钥那些怎么填了

**Comment by kuoihao** [comment]
更新了注释，试试看吧

**Comment by banfeng-git** [comment]
看到了但是不全面第一条run脚本是不是添加到serv00上如果是他怎么取名什么格式第二就是密钥填写的格式

**Comment by kuoihao** [comment]
run.sh放在~/下
run.sh这个脚本的命令，我是从教程中总结的https://saika.us.kg/2024/01/27/serv00_logs        
具体就是注释里那样，复制粘贴到run.sh就好，这个run.sh可以看自己需要执行什么任务而定。
密钥就是复制完了直接粘进去就可以，感谢补充。
